<?php

namespace app\controller;

use app\middleware\Admin;
use app\model\Bloque;
use app\model\Ente;
use app\model\Clap;
use app\model\Jefe;

class ClapsController extends Admin
{

    public string $TITTLE = 'Gestionar CLAPS';
    public string $MODULO = 'claps.index';

    public function isAdmin()
    {
        parent::isAdmin(); // TODO: Change the autogenerated stub
        if (!validarPermisos($this->MODULO)) {
            header('location: ' . ROOT_PATH . 'admin\\');
        }
    }


    public function listarBloques($municipio)
    {
        $model = new Bloque();
        $listarBloques = $model->getList('municipios_id', '=', $municipio);
        return $listarBloques;
    }

    public function listarEntes()
    {
        $model = new Ente();
        $listarBloques = $model->getAll();
        return $listarBloques;
    }

    public function listarClaps()
    {
        $model = new Clap();
        $listarClap = $model->getAll(1);
        return $listarClap;
    }



}