<?php

namespace app\controller;

use app\middleware\Admin;
use app\model\Cuota;
use app\model\Municipio;

class PagosController extends Admin
{
    public string $TITTLE = 'Validacion de pagos';
    public string $MODULO = 'pagos.index';

    public $linksPaginate;
    public $pag = 0;


    public function __construct($index = false)
    {
        parent::__construct($index);
        $this->mountMunicipios();
    }

    public function isAdmin()
    {
        parent::isAdmin(); // TODO: Change the autogenerated stub
        if (!validarPermisos($this->MODULO)) {
            header('location: ' . ROOT_PATH . 'admin\\');
        }
    }

    public function listarCuotas($municipio)
    {
        $model = new Cuota();
        $listarCuotas = $model->getList('municipios_id', '=', $municipio);
        return $listarCuotas;
    }
}