<?php

namespace app\controller;

use app\middleware\Admin;

class PagosController extends Admin
{
    public string $TITTLE = 'Validacion de pagos';
    public string $MODULO = 'pagos.index';

    public function isAdmin()
    {
        parent::isAdmin(); // TODO: Change the autogenerated stub
        if (!validarPermisos($this->MODULO)) {
            header('location: ' . ROOT_PATH . 'admin\\');
        }
    }


}