<?php

namespace app\controller;

use app\middleware\Admin;
use app\model\Parametros;

class ParametrosController extends Admin
{
    public $TITTLE = "Parametros";
    public $MODULO = "parametros.index";

    public $links;
    public $totalRows;
    public $limit;

    public function isAdmin()
    {
        parent::isAdmin(); // TODO: Change the autogenerated stub
        if ($this->USER_ROLE != 100){
            header('location: '. ROOT_PATH.'admin\\');
        }
    }


    public function listarParametros(): array
    {
        $model = new Parametros();
        $this->limit = numRowsPaginate();
        $this->totalRows = $model->count();
        $this->links = paginate('procesar.php','table_parametros', $this->limit, $this->totalRows, null, 'paginate', 'dataContainerParametros')->createLinks();
        return $model->paginate($this->limit,null, 'id','DESC');
    }



}