<?php

namespace app\controller;

use app\middleware\Admin;
use app\model\Municipio;
use app\model\Parroquia;

class TerritorioController extends Admin
{
    public string $TITTLE = 'Territorio';
    public string $MODULO = 'territorio.index';

    public $linksPaginate;
    public $pag = 0;

    public function isAdmin()
    {
        parent::isAdmin(); // TODO: Change the autogenerated stub
        if (!validarPermisos($this->MODULO)){
            header('location: '. ROOT_PATH.'admin\\');
        }
    }

    public function listarMunicipios(): array
    {
        $model = new Municipio();
        if (numRowsPaginate() < 15){$paginate = 15; }else{ $paginate = numRowsPaginate(); }
        $limit = $paginate;
        $this->linksPaginate = paginate('_request/MunicipiosRequest.php', 'tabla_municipios', $limit, $model->count(), null, 'paginate_municipio', 'dataContainerMunicipio', '_municipio')->createLinks();
        return $model->paginate($limit, null, 'nombre', 'ASC');
    }

    public function listarParroquias()
    {
        $model = new Parroquia();
        if (numRowsPaginate() < 15){$paginate = 15; }else{ $paginate = numRowsPaginate(); }
        $limit = $paginate;
        $this->linksPaginate = paginate('_request/ParroquiasRequest.php', 'tabla_parroquias', $limit, $model->count(), null, 'paginate_parroquia', 'dataContainerParroquia','_parroquia')->createLinks();
        return $model->paginate($limit, null, 'nombre', 'ASC');
    }

    public function getMunicipio($id)
    {
        $model = new Municipio();
        $municipio = $model->find($id);
        return $municipio['mini'];

    }




}