<?php

namespace app\controller;

use app\middleware\Admin;
use app\model\Municipio;
use app\model\Parroquia;

class TerritorioController extends Admin
{
    public string $TITTLE = 'Territorio';
    public string $MODULO = 'territorio.index';

    public $linksPaginate;
    public $pag = 0;

    public function isAdmin()
    {
        parent::isAdmin(); // TODO: Change the autogenerated stub
        if (!validarPermisos($this->MODULO)){
            header('location: '. ROOT_PATH.'admin\\');
        }
    }

    public function listarMunicipios(): array
    {
        $model = new Municipio();
        $limit = 15;
        $this->linksPaginate = paginate('procesar_municipio.php', 'tabla_municipios', $limit, $model->count(1), null, 'paginate_municipio', 'dataContainerMunicipio', '_municipio')->createLinks();
        return $model->paginate($limit, null, 'nombre', 'ASC', 1);
    }

    public function listarParroquias()
    {
        $model = new Parroquia();
        $limit = 15;
        $this->linksPaginate = paginate('procesar_parroquia.php', 'tabla_parroquias', $limit, $model->count(1), null, 'paginate_parroquia', 'dataContainerParroquia','_parroquia')->createLinks();
        return $model->paginate($limit, null, 'nombre', 'ASC', 1);
    }

    public function getMunicipio($id)
    {
        $model = new Municipio();
        $municipio = $model->find($id);
        return $municipio['nombre'];

    }




}